import type { Metadata } from "next";
import "./globals.css";
import { UIProvider } from "../../libs";
import Head from "next/head"; // Import Head from 'next/head'

export const metadata: Metadata = {
  title: "GlobalEthix",
  description: "Generated by GlobalEthix",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap"
        />
      </Head>
      <body className="bg-background-l0 overflow-x-hidden">
        <UIProvider>{children}</UIProvider>
      </body>
    </html>
  );
}
